apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-dashboard
  namespace: todo-dashboard
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: todo-dashboard.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: todo-dashboard
                port:
                  number: 80
