apiVersion: v1
kind: Service
metadata:
  name: todo-dashboard
  namespace: todo-dashboard
  labels:
    app: todo-dashboard
spec:
  type: ClusterIP
  selector:
    app: todo-dashboard
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
